const idSeed = require('./ids-data');

module.exports = {
  plataformOverviewOne: {
    _gameToken: idSeed.gameTokenOne,
    pacientId: idSeed.pacientIdOne,
    devices: ['Pitaco'],
    flowDataDevicesValues: [{
      deviceName: 'Pitaco',
      maxFlowValue: 10,
      minFlowValue: 0,
      meanFlowValue: 5,
    }],
    playStart: new Date(),
    playFinish: new Date(),
    duration: 0,
    result: 0,
    stageId: 0,
    phase: 0,
    level: 0,
    relaxTimeSpawned: 0,
    maxScore: 0,
    scoreRatio: 0,
    targetsSpawned: 0,
    TargetsSuccess: 0,
    TargetsInsSuccess: 0,
    TargetsExpSuccess: 0,
    TargetsFails: 0,
    TargetsInsFail: 0,
    TargetsExpFail: 0,
    ObstaclesSpawned: 0,
    ObstaclesSuccess: 0,
    ObstaclesInsSuccess: 0,
    ObstaclesExpSuccess: 0,
    ObstaclesFail: 0,
    ObstaclesInsFail: 0,
    ObstaclesExpFail: 0,
    PlayerHp: 100,
  },
  plataformOverviewTwo: {
    _gameToken: idSeed.gameTokenOne,
    pacientId: idSeed.pacientIdOne,
    devices: ['Pitaco', 'Cinta'],
    flowDataDevicesValues: [{
      deviceName: 'Pitaco',
      maxFlowValue: 100,
      minFlowValue: 0,
      meanFlowValue: 50,
    },
    {
      deviceName: 'Cinta',
      maxFlowValue: 100,
      minFlowValue: 0,
      meanFlowValue: 50,
    }],
    playStart: new Date(),
    playFinish: new Date(),
    duration: 0,
    result: 0,
    stageId: 0,
    phase: 0,
    level: 0,
    relaxTimeSpawned: 0,
    maxScore: 0,
    scoreRatio: 0,
    targetsSpawned: 0,
    TargetsSuccess: 0,
    TargetsInsSuccess: 0,
    TargetsExpSuccess: 0,
    TargetsFails: 0,
    TargetsInsFail: 0,
    TargetsExpFail: 0,
    ObstaclesSpawned: 0,
    ObstaclesSuccess: 0,
    ObstaclesInsSuccess: 0,
    ObstaclesExpSuccess: 0,
    ObstaclesFail: 0,
    ObstaclesInsFail: 0,
    ObstaclesExpFail: 0,
    PlayerHp: 100,
  },
};
