const mongoose = require('mongoose');

const PlataformOverviewSchema = mongoose.Schema({
  _gameToken: { type: String },
  pacientId: { type: String },
  gameDevice: { type: String },
  devices: [String],
  flowDataDevicesId: { type: mongoose.Schema.Types.ObjectId, ref: 'FlowDataDevice' },
  flowDataDevicesValues: [{
    deviceName: { type: String },
    maxFlowValue: { type: Number },
    minFlowValue: { type: Number },
    meanFlowValue: { type: Number },
  }],
  playStart: { type: Date },
  playFinish: { type: Date },
  duration: { type: Number },
  result: { type: Number },
  stageId: { type: Number },
  phase: { type: Number },
  level: { type: Number },
  relaxTimeSpawned: { type: Number },
  maxScore: { type: Number },
  scoreRatio: { type: Number },
  targetsSpawned: { type: Number },
  targetsSuccess: { type: Number },
  targetsInsSuccess: { type: Number },
  targetsExpSuccess: { type: Number },
  targetsFails: { type: Number },
  targetsInsFail: { type: Number },
  targetsExpFail: { type: Number },
  obstaclesSpawned: { type: Number },
  obstaclesSuccess: { type: Number },
  obstaclesInsSuccess: { type: Number },
  obstaclesExpSuccess: { type: Number },
  obstaclesFail: { type: Number },
  obstaclesInsFail: { type: Number },
  obstaclesExpFail: { type: Number },
  playerHp: { type: Number },
},
{ timestamps: { createdAt: 'created_at' } });

module.exports = mongoose.model('PlataformOverview', PlataformOverviewSchema);
